name: Commit Checks

on: [push]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: actions/cache@v3
      with:
        path: theme/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('theme/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    - uses: actions/cache@v3
      with:
        path: theme/vendor
        key: ${{ runner.os }}-composer-${{ hashFiles('theme/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Install npm
      run: |
        npm ci
    - name: Install composer
      run: |
        php8.1 $(which composer) install
    - name: Run lint
      run: |
        npm run lint
